AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 300
    MemorySize: 128

Resources:
  LadyClaudeApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: lady-claude-api
      OpenApiVersion: 3.0.0
      StageName: v1

  LadyClaudeReplyServiceTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: lady-claude-reply-service-topic

  LadyClaudeApiPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Events:
        LadyClaudeApiEvents:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId: !Ref LadyClaudeApiGateway
      FunctionName: lady-claude-api-post-function
      Handler: lady_claude.function.api.post.function.handler
      MemorySize: 512
      Role: !GetAtt LadyClaudeFunctionRole.Arn
      Runtime: python3.12

  # NOTE: 2024年9月1日からConnpassのスクレイピング禁止が明記されるため、一旦Connpassイベント通知機能も停止
  # LadyClaudeWorkerNotifyServiceConnpassFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: src
  #     EventInvokeConfig:
  #       MaximumRetryAttempts: 0
  #     Events:
  #       LadyClaudeScheduleEvent:
  #         Type: Schedule
  #         Properties:
  #           Schedule: "cron(0 23 ? * 7 *)"
  #           Name: lady-claude-notify-service-connpass-rule
  #     FunctionName: lady-claude-worker-notify-service-connpass-function
  #     Handler: lady_claude.function.worker.notify_service.connpass.function.handler
  #     Role: !GetAtt LadyClaudeFunctionRole.Arn
  #     Runtime: python3.12

  LadyClaudeWorkerNotifyServiceGarbageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Events:
        LadyClaudeScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: "cron(50 23 ? * 2,3,5,6 *)"
            Name: lady-claude-notify-service-garbage-rule
      FunctionName: lady-claude-worker-notify-service-garbage-function
      Handler: lady_claude.function.worker.notify_service.garbage.function.handler
      Role: !GetAtt LadyClaudeFunctionRole.Arn
      Runtime: python3.12

  LadyClaudeWorkerReplyServiceAskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Events:
        LadyClaudeSnsEvents:
          Type: SNS
          Properties:
            FilterPolicy:
              command:
                - ask
            Topic: !Ref LadyClaudeReplyServiceTopic
      FunctionName: lady-claude-worker-reply-service-ask-function
      Handler: lady_claude.function.worker.reply_service.ask.function.handler
      Role: !GetAtt LadyClaudeFunctionRole.Arn
      Runtime: python3.12

  LadyClaudeWorkerReplyServiceMinecraftFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Events:
        LadyClaudeSnsEvents:
          Type: SNS
          Properties:
            FilterPolicy:
              command:
                - minecraft
            Topic: !Ref LadyClaudeReplyServiceTopic
      FunctionName: lady-claude-worker-reply-service-minecraft-function
      Handler: lady_claude.function.worker.reply_service.minecraft.function.handler
      Role: !GetAtt LadyClaudeFunctionRole.Arn
      Runtime: python3.12

  LadyClaudeWorkerReplyServiceRecipeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Events:
        LadyClaudeSnsEvents:
          Type: SNS
          Properties:
            FilterPolicy:
              command:
                - recipe
            Topic: !Ref LadyClaudeReplyServiceTopic
      FunctionName: lady-claude-worker-reply-service-recipe-function
      Handler: lady_claude.function.worker.reply_service.recipe.function.handler
      Role: !GetAtt LadyClaudeFunctionRole.Arn
      Runtime: python3.12

  LadyClaudeFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: lady-claude-function-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - bedrock:InvokeModel
                  - ec2:DescribeInstances
                  - ec2:StartInstances
                  - ec2:StopInstances
                  - s3:GetObject
                  - s3:PutObject
                  - sns:Publish
                  - sns:Subscribe
                  - ssm:GetParameter
                  - ssm:GetCommandInvocation
                  - ssm:SendCommand
                Resource: "*"
      RoleName: lady-claude-function-role

  LadyClaudeReplyServiceTopicArnParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: /LADY_CLAUDE/REPLY_SERVICE/TOPIC_ARN
      Type: String
      Value: !Ref LadyClaudeReplyServiceTopic
